### ISSUE TITLE
[Question] What is the correct transformation matrices of MICO?

### ISSUE THREAD

**Issue by mu-777** [Kinovarobotics/kinova-ros#54]
Hello,

I need the transformation matrices of MICO to control it.
Now I'm using the matrices referring to the comments on `jaco_arm_kinematics.cpp`.
However, tfs from `jaco_tf_updater.cpp` (which uses `jaco_arm_kinematics.cpp`, you may know) is different from tfs from MICO's urdf.

Which is the same as the real MICO configulations?
How can I know the transformation matrices of MICO?

thanks.

**Comment by mklingen** [comment]
I'm just bumping this because I have also noticed that the kinematics defined in the URDF are completely different than those defined in `jaco_arm_kinematics.cpp`. The hardcoded kinematics in `jaco_arm_kinematics.cpp` are much closer to correct than the kinematics in the URDF. Sometimes, the tool frame can be off by as much as 10 cm(!). This is very bad news for anyone using the mico arm driver with ROS. I'm going to take a close look at this in the coming weeks and try to come up with a solution.

**Comment by mklingen** [comment]
Pinging @francoisferland or anyone else who worked on the URDF.

**Comment by francoisferland** [comment]
Hi,

It has been a while since I worked on the URDF and I no longer have access to the physical robots, but it sounds like a mix-up between the latest URDF version and the old version of the driver. I think the latest, correct version of the driver is still in the "fferland_newapi" branch, not on the master one. If you look at jaco_arm.cpp in that branch, the J5 offset error you mention in #58 should be fixed.

Hope this helps!

**Comment by mklingen** [comment]
@francoisferland thank you very much. I have pulled from `fferland_newapi`. While it does fix the PI/2 offset of J6, it does not solve all the problems with the URDF. Here are a couple of screenshots of the tool frame reported by the driver as compared to the URDF. The tool frame is supposed to be aligned with the axis of J6, and located between the fingers. 

![kinova_mico_urdf2](https://cloud.githubusercontent.com/assets/241184/13351756/e4ff6ce2-dc80-11e5-8e92-68c7bd69be16.png)
![kinova_mico_urdf](https://cloud.githubusercontent.com/assets/241184/13351757/e67119a4-dc80-11e5-912e-a139cb6a1ff1.png)

**Comment by mklingen** [comment]
It looks like most of the problem is with J2 and J3, as you can see in this image. 

![bad_urdf1](https://cloud.githubusercontent.com/assets/241184/13352301/42099d6a-dc84-11e5-9610-1541ea322b32.png)

![20160226_122109](https://cloud.githubusercontent.com/assets/241184/13352303/452f0ebc-dc84-11e5-9e91-36d0ad712cac.jpg)

J1 is supposed to make a nearly right angle with the base here, and J2 is a nearly right angle with link 1. The joint angles reported by the firmware also make sense for this configuration (~270 degrees and ~90 degrees).

**Comment by francoisferland** [comment]
You are right, there seem to be an offset on J2-3. I don't remember seeing this before.

My first guest was that there is also an API offset setting shared between the driver and the hardware controller. That offset is meant to adjust the zero point for cartesian commands. The tool topic is coming straight from the low level API, and (I think) includes this offset. However, it might not be attached to the correct URDF frame, or that frame does not have the proper offset. For that, you could always measure the inverse transform and re-publish it as a correction TF frame, but it wouldn't solve what you see in the second picture.

Another way to test it would be a completely straight pose (pointing to the ceiling). You could then try adjusting that offset in the angle conversion code. Otherwise I would suggest reaching Kinova support directly. As I'm no longer affiliated with them I can't really help beyond that.

**Comment by mklingen** [comment]
Thank you very much for helping me understand this issue. I have noticed that there are parameters for joint offsets in the `jaco_arm_kinematics` module. Do you know if these parameters are supposed to be calibrated for each robot, or if they are fixed?

Looking at the robot configuration when its straight up, I can definitely see that the error is just with J2 it seems.

![mico_straightup](https://cloud.githubusercontent.com/assets/241184/13352847/09397a7e-dc88-11e5-8fd5-b80aad0528f8.png)

**Comment by francoisferland** [comment]
As far as I know, they should be fixed from the factory.

**Comment by mklingen** [comment]
I fixed it!! It all comes down to this line:

https://github.com/Kinovarobotics/kinova-ros/blob/551a13503912ad3818e88e16cd7a69a21c7cdde3/jaco_driver/src/jaco_arm.cpp#L334

Why is the offset randomly set to 260 degrees instead of 270 for mico arms!? Crazy!

**Comment by francoisferland** [comment]
I vaguely remember this being an issue at one point, but I'm surprised it's still the case... Maybe something else changed since last time I looked at it. Anyway, I'm happy you fixed your issue!

François
